### ISSUE TITLE
Variadic arguments in `perform` are troublesome

### ISSUE THREAD

**Issue by vjpr** [bmeck/understudy#12]
Say I set an `after` hook on an event and forget to pass the right arguments, it ends up in a lot of silent failures. There should be an assertion of number of arguments.

**Comment by jcrugzz** [comment]
@vjpr we usually use a single `options` object for this very reason. Keeps it simple. You define the arguments that everything expects when you call `perform`. Not sure there is a performant way to make sure the before and after hooks conform to that. Would accept a PR if you want to take a stab at it if it doesnt reduce perf

**Comment by indexzero** [comment]
@vjpr I wanted to say "pull-request welcome", but then I realized that there is no good way to support this case:

```
var study = new Understudy();
study.before(function () {
  var args = Array.prototype.slice.call(arguments);
  var next = args.pop();

  // Do valid stuff with all the other arguments
  next();
});
```

Since arity of the function can't be inferred from `function.length` this becomes a very difficult problem to solve well.

**Comment by indexzero** [comment]
With that in mind @vjpr if you can find a solution that supports all the edge cases we would accept the PR.

**Comment by vjpr** [comment]
Thanks guys. For now I will just make it convention to pass a single `options` to every call. Might take a look at it again later.
